### ISSUE TITLE
libMagick++.so.5 is missing

### ISSUE THREAD

**Issue by jalik** [elad/node-imagemagick-native#115]
Hi, I am trying to use imagemagick-native with the Meteor JS framework, in the past I successfully installed and used it, but with Ubuntu 15.10 I have a lot of problems.

I installed packages :
apt-get install libmagick++-dev imagemagick

To install the module with NPM, I had to workaround because it did not find Magick++-Config :
export PATH=$PATH:/usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/bin-Q16/

And now when I start my app with node I get :
I really need help, because currently this error happens on my DEV environment and I cannot deploy on my PROD env since it would break the website...

Error: libMagick++.so.5: cannot open shared object file: No such file or directory                                                   
    at Module.load (module.js:356:32)                                                                                                
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/eshipp/bundle/programs/server/npm/eshipp_avatars/node_modules/imagemagick-native/index.js:1:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by faninv** [comment]
+1

**Comment by CherryDT** [comment]
After the dist upgrade, you have to rebuild the npm package.

In my case, there was also the Magic++-config program not in the path, so I had to do:

```
PATH=/usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/bin-Q16:$PATH npm rebuild imagemagick-native
```

**Comment by anilkumar20** [comment]
same error
