### ISSUE TITLE
Module version mismatch. Expected 43, got 14.                                                while running sample program.

### ISSUE THREAD

**Issue by kamaldeepoodles** [elad/node-imagemagick-native#116]
I installed the **imagemagick-native** using command- npm install imagemagick-native
The module is successfully installed with the following log

```console
C:\Users\xz\Downloads\test\examples>npm install imagemagick-native

> imagemagick-native@1.8.0 install C:\Users\xz\Downloads\test\examples\node_modules\imagemagick-native
> node-gyp rebuild


C:\Users\xz\Downloads\test\examples\node_modules\imagemagick-native>if not defined npm_config_node_gyp (node "C:\Users\xz\AppData\Roaming\nvm\v0.12.7\node_modules\npm\bin
\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  imagemagick.cc
c:\program files\imagemagick-6.8.5-q16\include\magick/pixel-accessor.h(163): warning C4244: 'argument' : conversion from 'double' to 'const MagickCore::MagickRealType',
possible loss of data [C:\Users\xz\Downloads\test\examples\node_modules\imagemagick-native\build\imagemagick.vcxproj]
C:\Program Files\Microsoft Visual Studio 10.0\VC\include\xlocale(323): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:
\Users\xz\Downloads\test\examples\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(131): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\Users\xz\Downloads\test\examples\node_modu
les\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(304): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\Users\xz\Downloads\test\examples\node_modu
les\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(344): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\Users\xz\Downloads\test\examples\node_modu
les\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(364): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\Users\xz\Downloads\test\examples\node_modu
les\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(405): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\Users\xz\Downloads\test\examples\node_modu
les\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(572): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\Users\xz\Downloads\test\examples\node_modu
les\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(742): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\Users\xz\Downloads\test\examples\node_modu
les\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(817): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\Users\xz\Downloads\test\examples\node_modu
les\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(890): warning C4344: behavior change: use of explicit template arguments results in call to 'v8::Local<T> NanNew<v8::String,char*>(A0)' [C:\Users\x
z\Downloads\test\examples\node_modules\imagemagick-native\build\imagemagick.vcxproj]
          with
          [
              T=v8::String,
              A0=char *
          ]
          but the regular function 'v8::Local<T> NanNew(const char *)' is a better match
          with
          [
              T=v8::String
          ]
          if you expect 'v8::Local<T> NanNew(const char *)' to be called then you need to make it an explicit specialization
          with
          [
              T=v8::String
          ]
  win_delay_load_hook.c
     Creating library C:\Users\xz\Downloads\test\examples\node_modules\imagemagick-native\build\Release\imagemagick.lib and object C:\Users\xz\Downloads\test\examples\no
  de_modules\imagemagick-native\build\Release\imagemagick.exp
  Generating code
  Finished generating code
  imagemagick.vcxproj -> C:\Users\xz\Downloads\test\examples\node_modules\imagemagick-native\build\Release\\imagemagick.node
PacificCX@0.0.1 C:\Users\xz\Downloads\test\examples
└── imagemagick-native@1.8.0  extraneous


C:\Users\xz\Downloads\test\examples>
```

Now after installation, I tried to run the sample program

```javascript
var imagemagick = require('imagemagick-native');
imagemagick.writeFileSync('image.jpg', imagemagick.convert({
    srcData: fs.readFileSync('before.jpg'),
    format: 'PNG',
    quality: 100 // (best) to 1 (worst)
}));
```

But got the following error...

![webkit3](https://cloud.githubusercontent.com/assets/10527158/11955884/cc1e89c0-a8db-11e5-819a-d4c6a43a26b4.jpg)

Please look into the issue and oblige.

**Comment by randianb** [comment]
+1

**Comment by elad** [comment]
I don't use Windows and don't plan on supporting it. Unless someone steps up to fix it, I'll just remove support for the platform or mark it as "experimental."

**Comment by telekosmos** [comment]
Hi there
We have the same problem with `node >= 4.x` on __OSX 10.11__ (actually, we tried `node 4.2.2` and `node 6.5.0`). We are running an __express API__ and __imagemagick__ makes operations on uploaded pics. It is working with `node 0.12.12` (:-S). With `node 6.5.0`, trying to startup the express app shows the following error:
```
module.js:460
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 46, got 14.
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/telekosmos/DevOps/lingbe/lingbe-api/node_modules/imagemagick-native/index.js:1:80)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/telekosmos/DevOps/lingbe/lingbe-api/services/MediaService.js:5:19)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
``` 

Any hint about it? 

thanks!!!

**Comment by elad** [comment]
Sorry, no idea... To be honest, I barely have time to maintain this module. You should check out and see if [Sharp](https://github.com/lovell/sharp) or [Jimp](https://github.com/oliver-moran/jimp) fit better for your purposes.

**Comment by telekosmos** [comment]
Thanks for the quick reply!!! 
Will take a look to those modules, trying to bump the node version to support our app with last features.

Cheers again

**Comment by cartuchogl** [comment]
@telekosmos your problem is that a native module compiled with a version of node is not compatible with other. If you remove imagemagick-native and reinstall using 6.x that would be fine.

**Comment by telekosmos** [comment]
@cartuchogl many thanks, that worked perfectly :-) so far. In addition, packeges named by @elad are worth to see for those starting new projects.
