### ISSUE TITLE
Install imagemagick-native on windows 7 errors

### ISSUE THREAD

**Issue by jmorrisIII** [elad/node-imagemagick-native#129]
I'm having errors when trying to install imagemagick-native on windows 7 64. Not sure which of the errors are fatal.

```
E:\WebstormProjects\innovation-node-server>npm install imagemagick-native --save
npm WARN package.json nodedev@1.0.0 No repository field.
npm WARN package.json nodedev@1.0.0 No README data
-
> imagemagick-native@1.9.2 install E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native
> node-gyp rebuild


E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  imagemagick.cc
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
C:\Users\James.Morris\.node-gyp\0.10.32\deps\uv\include\uv.h(1563): error C2079: 'uv_fs_s::statbuf' uses undefined struct '_stat64' [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(112): warning C4267: 'argument' : conversion from 'size_t' to 'uint32_t', possible loss of data [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(245): error C2039: 'FilterTypes' : is not a member of 'Magick' [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(245): error C2065: 'FilterTypes' : undeclared identifier [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(245): error C2146: syntax error : missing ')' before identifier 'option_info' [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(245): error C2059: syntax error : ')' [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(260): warning C4267: '=' : conversion from 'size_t' to 'unsigned int', possible loss of data [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(261): warning C4267: '=' : conversion from 'size_t' to 'unsigned int', possible loss of data [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(310): error C2661: 'Magick::Geometry::Geometry' : no overloaded function takes 6 arguments [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(328): error C2661: 'Magick::Geometry::Geometry' : no overloaded function takes 6 arguments [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(334): error C2039: 'alpha' : is not a member of 'Magick::Color' [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
          c:\program files\imagemagick-7.0.1-q16\include\Magick++/Color.h(35) : see declaration of 'Magick::Color'
..\src\imagemagick.cc(408): error C2664: 'Magick::Point Magick::Image::density(void) const' : cannot convert argument 1 from 'Magick::Geometry' to 'const Magick::Point &' [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
          Reason: cannot convert from 'Magick::Geometry' to 'const Magick::Point'
          No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
..\src\imagemagick.cc(782): error C2039: 'PixelPacket' : is not a member of 'Magick' [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(782): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(782): error C2143: syntax error : missing ';' before '*' [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(782): error C2065: 'pixels' : undeclared identifier [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(786): error C2039: 'PixelPacket' : is not a member of 'Magick' [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(786): error C2146: syntax error : missing ';' before identifier 'pixel' [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(786): error C2065: 'pixel' : undeclared identifier [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(786): error C2065: 'pixels' : undeclared identifier [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(789): error C2065: 'pixel' : undeclared identifier [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(789): error C2228: left of '.red' must have class/struct/union [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
          type is 'unknown-type'
..\src\imagemagick.cc(789): error C2661: 'v8::Object::Set' : no overloaded function takes 1 arguments [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(790): error C2065: 'pixel' : undeclared identifier [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(790): error C2228: left of '.green' must have class/struct/union [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
          type is 'unknown-type'
..\src\imagemagick.cc(790): error C2661: 'v8::Object::Set' : no overloaded function takes 1 arguments [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(791): error C2065: 'pixel' : undeclared identifier [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(791): error C2228: left of '.blue' must have class/struct/union [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
          type is 'unknown-type'
..\src\imagemagick.cc(791): error C2661: 'v8::Object::Set' : no overloaded function takes 1 arguments [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(792): error C2065: 'pixel' : undeclared identifier [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(792): error C2228: left of '.opacity' must have class/struct/union [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
          type is 'unknown-type'
..\src\imagemagick.cc(792): error C2661: 'v8::Object::Set' : no overloaded function takes 1 arguments [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(853): error C2661: 'Magick::Geometry::Geometry' : no overloaded function takes 6 arguments [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(863): error C2039: 'PixelPacket' : is not a member of 'Magick' [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(863): error C2065: 'PixelPacket' : undeclared identifier [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(863): error C2065: 'pixels' : undeclared identifier [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(865): error C2039: 'PixelPacket' : is not a member of 'Magick' [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(865): error C2065: 'PixelPacket' : undeclared identifier [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(865): error C2065: 'colors' : undeclared identifier [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(865): error C2061: syntax error : identifier 'PixelPacket' [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(870): error C2039: 'PixelPacket' : is not a member of 'Magick' [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(870): error C2065: 'PixelPacket' : undeclared identifier [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(870): error C2146: syntax error : missing ';' before identifier 'pixel' [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(870): error C2065: 'pixel' : undeclared identifier [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(870): error C2065: 'pixels' : undeclared identifier [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(874): error C2065: 'pixel' : undeclared identifier [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(874): error C2228: left of '.red' must have class/struct/union [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
          type is 'unknown-type'
..\src\imagemagick.cc(874): error C2065: 'colors' : undeclared identifier [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(874): error C2228: left of '.green' must have class/struct/union [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
          type is 'unknown-type'
..\src\imagemagick.cc(874): error C2228: left of '.blue' must have class/struct/union [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
          type is 'unknown-type'
..\src\imagemagick.cc(876): error C2065: 'colors' : undeclared identifier [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(876): error C2065: 'pixel' : undeclared identifier [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(885): error C2065: 'colors' : undeclared identifier [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(885): error C2228: left of '.red' must have class/struct/union [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(885): error C2228: left of '.green' must have class/struct/union [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(885): error C2228: left of '.blue' must have class/struct/union [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(890): error C2065: 'colors' : undeclared identifier [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(890): error C2228: left of '.red' must have class/struct/union [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(893): error C2065: 'colors' : undeclared identifier [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(893): error C2228: left of '.green' must have class/struct/union [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(896): error C2065: 'colors' : undeclared identifier [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(896): error C2228: left of '.blue' must have class/struct/union [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(910): error C2065: 'colors' : undeclared identifier [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
..\src\imagemagick.cc(910): error C2541: 'delete' : cannot delete objects that are not pointers [E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native\build\imagemagick.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\WebstormProjects\innovation-node-server\node_modules\imagemagick-native
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! imagemagick-native@1.9.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the imagemagick-native@1.9.2 install script.
npm ERR! This is most likely a problem with the imagemagick-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls imagemagick-native
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "imagemagick-native" "--save"
npm ERR! cwd E:\WebstormProjects\innovation-node-server
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by pfjare** [comment]
Any luck on this?

**Comment by jmorrisIII** [comment]
No.

**Comment by buddhabuddy** [comment]
What version of ImageMagick have you installed?  I had similar issue with v7. Try a v6.x.x from ftp://ftp.imagemagick.org/pub/ImageMagick/binaries/

**Comment by rmoni3000** [comment]
> What version of ImageMagick have you installed? I had similar issue with v7. Try a v6.x.x from ftp://ftp.imagemagick.org/pub/ImageMagick/binaries/

Downgraded to v6 and worked like a charm, thanks a lot!
