### ISSUE TITLE
build broken for node version 5.5.0 on osx 10.10.5

### ISSUE THREAD

**Issue by WestleyArgentum** [elad/node-imagemagick-native#131]
I can't install at all:

```
➜  code mkdir test
➜  code cd test
➜  test node --version
v5.5.0
➜  test npm install imagemagick-native

> imagemagick-native@1.9.2 install /Users/westleyhennigh/code/test/node_modules/imagemagick-native
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
/bin/sh: Magick++-config: command not found
gyp: Call to 'Magick++-config --ldflags --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/westleyhennigh/.nvm/versions/node/v5.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/westleyhennigh/.nvm/versions/node/v5.5.0/bin/node" "/Users/westleyhennigh/.nvm/versions/node/v5.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/westleyhennigh/code/test/node_modules/imagemagick-native
gyp ERR! node -v v5.5.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/Users/westleyhennigh/code/test/package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/westleyhennigh/.nvm/versions/node/v5.5.0/bin/node" "/Users/westleyhennigh/.nvm/versions/node/v5.5.0/bin/npm" "install" "imagemagick-native"
npm ERR! node v5.5.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! imagemagick-native@1.9.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the imagemagick-native@1.9.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the imagemagick-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs imagemagick-native
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls imagemagick-native
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/westleyhennigh/code/test/npm-debug.log
```

Is there something else I need to install or build?

**Comment by elad** [comment]
The library & headers...
