### ISSUE TITLE
Win10 x64  SyntaxError: invalid syntax @ print get_regvalue('SOFTWARE\\ImageMagick\\Current', 'LibPath')

### ISSUE THREAD

**Issue by buddhabuddy** [elad/node-imagemagick-native#158]
C:\Users\guy\AppData\Roaming\npm>npm install imagemagick-native

> imagemagick-native@1.9.3 install C:\Users\guy\AppData\Roaming\npm\node_modules\imagemagick-native
> node-gyp rebuild

C:\Users\guy\AppData\Roaming\npm\node_modules\imagemagick-native>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
  File "get_regvalue.py", line 16
    print get_regvalue('SOFTWARE\\ImageMagick\\Current', 'LibPath')
                     ^
SyntaxError: invalid syntax
gyp: Call to 'python get_regvalue.py' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\guy\AppData\Roaming\npm\node_modules\imagemagick-native
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "imagemagick-native"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! imagemagick-native@1.9.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the imagemagick-native@1.9.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the imagemagick-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs imagemagick-native
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls imagemagick-native
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\guy\AppData\Roaming\npm\npm-debug.log

**Comment by buddhabuddy** [comment]
it was still running python 3, once removed and properly set python 2.7 in path, all sorted.
