### ISSUE TITLE
Error while installing 

### ISSUE THREAD

**Issue by LizanLycan** [elad/node-imagemagick-native#168]
**DESCRPTION**
I have a problem trying to install the package. Install all dependencies that require, except ImageMagick, install this (ImageMagick-6.9.8-8-Q16-HDRI-x64-dll.exe)

**ERROR**
c:\Proyect-path\node_modules\nan\nan_new.h(208): error C2668: 'Nan::mp::IntegerFactory<v8::Int
eger>::New': ambiguous call to overloaded function (compiling source file ..\src\imagemagick.cc) 
[C:\Proyect-path\node_modules\imagemagick-native\build\imagemagick.vcxproj]
  c:\Proyect-path\node_modules\nan\nan_new.h(114): note: could be 'v8::Local<v8::Integer> Nan::
  imp::IntegerFactory<v8::Integer>::New(uint32_t)' (compiling source file ..\src\imagemagick.cc)
  c:\Proyect-path\node_modules\nan\nan_new.h(113): note: or       'v8::Local<v8::Integer> Nan::
  imp::IntegerFactory<v8::Integer>::New(int32_t)' (compiling source file ..\src\imagemagick.cc)
  c:\Proyect-path\node_modules\nan\nan_new.h(208): note: while trying to match the argument lis
  t '(MagickCore::Quantum)' (compiling source file ..\src\imagemagick.cc)
  ..\src\imagemagick.cc(810): note: see reference to function template instantiation 'v8::Local<v8::Integer> Nan::New<v8::Integer,MagickCore::Quantum>(A0)' being compi
  led
          with
          [
              A0=MagickCore::Quantum
          ]
Compilación del proyecto terminada "C:\Proyect-path\node_modules\imagemagick-native\build\image
magick.vcxproj" (destinos predeterminados) -- ERROR.

Compilación del proyecto terminada "C:\Proyect-path\node_modules\imagemagick-native\build\bindi
ng.sln" (destinos predeterminados) -- ERROR.

ERROR al compilar.

"C:\Proyect-path\node_modules\imagemagick-native\build\binding.sln" (destino predeterminado) (1
) ->
"C:\Proyect-path\node_modules\imagemagick-native\build\imagemagick.vcxproj" (destino predetermi
nado) (2) ->
(ClCompile destino) ->
  ..\src\imagemagick.cc(113): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data 
  [C:\Proyect-path\node_modules\imagemagick-native\build\imagemagick.vcxproj]
  ..\src\imagemagick.cc(139): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc 
  [C:\Proyect-path\node_modules\imagemagick-native\build\imagemagick.vcxproj]
  ..\src\imagemagick.cc(277): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data 
  [C:\Proyect-path\node_modules\imagemagick-native\build\imagemagick.vcxproj]
  ..\src\imagemagick.cc(278): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data 
  [C:\Proyect-path\node_modules\imagemagick-native\build\imagemagick.vcxproj]

"C:\Proyect-path\node_modules\imagemagick-native\build\binding.sln" (destino predeterminado) (1
) ->
"C:\Proyect-path\node_modules\imagemagick-native\build\imagemagick.vcxproj" (destino predetermi
nado) (2) ->
(ClCompile destino) ->
  c:\Proyect-path\node_modules\nan\nan_new.h(208): error C2668: 'Nan::mp::IntegerFactory<v8::I
nteger>::New': ambiguous call to overloaded function (compiling source file ..\src\imagemagick.cc) 
[C:\Proyect-path\node_modules\imagemagick-native\build\imagemagick.vcxproj]

    4 Advertencia(s)
    1 Errores

Tiempo transcurrido 00:00:05.67
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Proyect-path\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\Proyect-path\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Proyect-path\node_modules\imagemagick-native
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok
npm verb lifecycle imagemagick-native@1.9.3~install: unsafe-perm in lifecycle true

**Comment by bugparty** [comment]
same here
