### ISSUE TITLE
Can't install on OSX 

### ISSUE THREAD

**Issue by yvoxu** [elad/node-imagemagick-native#190]
Trying to install this package and the error is following:
fatal error: too many errors emitted, stopping now [-ferror-limit=]
33 warnings and 20 errors generated.
make: *** [Release/obj.target/imagemagick/src/imagemagick.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/Cellar/node/11.2.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/yvonnexu/code/lpr/node_modules/imagemagick-native
gyp ERR! node -v v11.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN lpr@1.0.0 No description
npm WARN lpr@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! imagemagick-native@1.9.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the imagemagick-native@1.9.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yvonnexu/.npm/_logs/2018-11-26T04_21_33_499Z-debug.log

There's a list of errors occured above these codes. I didn't post it cause it is wayyyyyyy too long! I've also had node-imagemagick installed.

**Comment by yvoxu** [comment]
I reckon I was working with master branch?
Yeah unfortunately, I used gm npm package instead eventually..
Thanks for answering my question!
